### PR TITLE
updating readme to show configuration options

### PR DESCRIPTION
**Pull request by jaredwray**
**Please check if the PR fulfills these requirements**
- [x] Followed the [Contributing](https://github.com/node-cache-manager/node-cache-manager/blob/main/CONTRIBUTING.md) guidelines.
- [x] Tests for the changes have been added (for bug fixes/features) with 100% code coverage.
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
updating readme to show configuration options

### CODE REVIEW

**Comment by adelbke** [comment]
Thanks for replying.

I checked the code and in the memory cache shouldCloneBeforeSet is set to true by default. As indicated [here](https://github.com/node-cache-manager/node-cache-manager/blob/749997451e333a389e2cde68cd13a0c3879445ee/src/stores/memory.ts#L37)

**Comment by adelbke** [comment]
Unless I am missing something, please let me know if I did.

**Comment by jaredwray** [comment]
@adelbke - LOL I was going too fast. Good catch. Updated here: https://github.com/node-cache-manager/node-cache-manager/pull/645

**Comment by adelbke** [comment]
Yeah...it happens to everyone, even the best 😅

**Comment by jaredwray** [comment]
> Yeah...it happens to everyone, even the best 😅

😂

**Pull request merged**
