### PR TITLE
feat: optional refresh strategy (stale-while-revalidate) #533

### PR DESCRIPTION
**Pull request by jonathanarezki**
Added refresh threshold, to update stores before the ttl runs out.
Only the wrap function is affected.
If the the remaining ttl of a store is smaller than the refresh threshold,
the store gets set with the fn asynchronously.
The refresh threshold is optional and is not stored in the store it self, only in the cache instance as a config.

### CODE REVIEW

**Comment by jaredwray** [comment]
@jonathanarezki thanks for doing this pull request. I will be reviewing this in the next 10 days and get back to you on this.

**Comment by jaredwray** [comment]
Also, please make sure to update your branch to the latest.

**Comment by jaredwray** [comment]
@jonathanarezki can you update the readme with this new functionality?

**Comment by jonathanarezki** [comment]
I updated the readme.

**Review by jaredwray — APPROVED** [review]

**Comment by jaredwray** [comment]
@jonathanarezki - thanks and since this is not a non breaking change I will add it to the next release which should go out in the next couple weeks.

**Comment by jonathanarezki** [comment]
Thank you really much. I didn't expect it to go that smooth.

**Pull request merged**
