### PR TITLE
Add refreshThreshold as parameter of wrap function. Fix #606

### LINKED ISSUE #606: Adding  refreshThreshold Parameter to the wrap Function
The cache's  TTL can vary significantly, for instance, between 5 minutes and 1 day. It's challenging to determine a single, unified refreshThreshold setting for all use cases. Therefore, adding a separate refreshThreshold parameter to the wrap function could be a valuable enhancement.

### PR DESCRIPTION
**Pull request by lchenay**
**Please check if the PR fulfills these requirements**
- [x] Followed the [Contributing](https://github.com/node-cache-manager/node-cache-manager/blob/main/CONTRIBUTING.md) guidelines.
- [ ] Tests for the changes have been added (for bug fixes/features) with 100% code coverage.
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

### CODE REVIEW

**Comment by jaredwray** [comment]
@lchenay - thanks for putting this together. Could you make sure to update the unit tests on this and also update the documentation?

**Comment by jaredwray** [comment]
@lchenay - any update on this?

**Comment by jaredwray** [comment]
@lchenay  - any update on this? If not, I will close it out.

**Comment by lchenay** [comment]
On it. Doing all this WE.

**Comment by lchenay** [comment]
620dd3f424431f00b0362f03f2dc0ad567f9f3b3 is not directly related to this PR.
I can extract them to a new PR if interested and needed.

**Comment by jaredwray** [comment]
@lchenay - thanks so much. merging this now.

**Pull request merged**
