### PR TITLE
Breaking out of asyncSeries loop when value is found. Controlled via new options function isReturnableValue.

### PR DESCRIPTION
**Pull request by 3choBoomer**

### CODE REVIEW

**Comment by PuKoren** [comment]
If you just check for ``result`` var I think you won't break out of async loop in cases where cached value is a falsey (false, "", 0, etc.)

Maybe I'm mistaken, is it expected behaviour?

**Comment by 3choBoomer** [comment]
@PuKoren my thought there was that the expense of getting a falsey value from a cache is extremely cheap compared to non-falsey values like large strings. (which is the specific use case I'm attempting to solve for here).

I'm working on doing this another way that came out of my discussion with @BryanDonovan here:
https://github.com/BryanDonovan/node-cache-manager/issues/41

**Comment by BryanDonovan** [comment]
Sorry @3choBoomer -- I didn't see your comment here.  Can you merge the latest from upstream/master and add the same `isReturnableValue` logic to `lib/caching.js` as well please?  Then I think it's good to go.

**Comment by botika** [comment]
Closed by refactor #203

**Pull request closed without merging**
