### PR TITLE
Use a github action workflow to release new versions

### PR DESCRIPTION
**Pull request by QuentinLemCode**
Hello

Following the empty 5.3.0 version on NPM, I suggest to use an automated workflow to avoid this in the future.

This PR add a github action workflow to perform automated releases.

The release workflow can only be launched manually with a choice for the type of release (major, minor, patch).
You can add a release message.

Required : Add the NPM authentication token inside repository secrets with the name `NPM_AUTH_TOKEN`

### CODE REVIEW

**Comment by TheAlan404** [comment]
is a `.npmignore` also needed here?

**Comment by QuentinLemCode** [comment]
> is a `.npmignore` also needed here?

Yes I add it

**Review by alumni — APPROVED** [review]

**Comment by alumni** [comment]
@jaredwray could you please review this? thanks!

**Review by TheAlan404 — APPROVED** [review]

**Comment by QuentinLemCode** [comment]
We also need to add the package-lock because the `npm version` will fail as the `npm install` will create the file and make `npm version` because of pending changes.

**Comment by QuentinLemCode** [comment]
> @QuentinLemCode - thanks for the update on this and we might want to get something a bit more simple where we arent doing the version bump in the code. Either way, I can do an update on that after the merge.

@jaredwray You are welcome
Yes we can do that and trigger the publish on a new release
Don't hesitate to comment the review, I will be happy to help

**Comment by jaredwray** [comment]
@QuentinLemCode thanks so much for the work on this. 

@guslen  - I will be doing some tweaks to this to simplify it down but if you have any suggestions let me know and feel free to create an issue to dialogue about it first.

**Pull request merged**
